on: [push]

name: AzureCLIStop

jobs:

    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Azure Login
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Run Azure CLI ps1 script
          shell: pwsh
          run: |
            .\deployappservice.ps1

