on:
  push:
    paths:
      - 'startappservice.ps1'
  workflow_dispatch:

name: AzureCLIStartappservice

jobs:

    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Azure Login
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Run Azure CLI ps1 script
          shell: pwsh
          run: |
            .\startappservice.ps1 `
              -serviceprincipalAppId "${{ secrets.AZURE_CREDENTIALS.clientId }}" `
              -sppassword "${{ secrets.AZURE_CREDENTIALS.clientSecret }}" `
              -tenantId "${{ secrets.AZURE_CREDENTIALS.tenantId }}"

